Blog/urls.py
from django.urls import path
from Blog.views import (ArticlesView, ClaimView, ContentPage, HomePage, EditPage,
                        LoginView, SignupView, LogoutView)

app_name = 'Blog'
urlpatterns = [
    path('', HomePage.as_view(), name="homepage"),
    path('<int:id>', ContentPage.as_view(), name="Content"),
    path('<int:id>/edit/<secret_key>', EditPage.as_view(), name="editPage"),
    path('<int:id>/edit/', EditPage.as_view(), name="LogUserEdit"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('mine/', ArticlesView.as_view(), name="mine"),
    path('<int:id>/claim/<secret_key>', ClaimView.as_view(), name="Claim"),
]

djangoprojects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Blog.urls')),
    path('admin/', admin.site.urls),
]

Blog/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
# Create your models here.


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    content = models.CharField(validators=[MinLengthValidator(10)], max_length=300)
    title = models.CharField(validators=[MinLengthValidator(10)], max_length=50)
    secret_key = models.CharField(max_length=20)

    def __str__(self):
        return self.title

Blog/forms.py
from .models import Blog
from django.contrib.auth.models import User
from django import forms
import bleach

VALID_TAGS = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']


class BlogForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'content'}))

    class Meta:
        model = Blog
        fields = ["content", "title"]

    def clean(self):
        super().clean()
        cleaned_data = self.cleaned_data
        title = cleaned_data.get("title")
        content = cleaned_data.get("content")
        if len(content) < len(title):
            raise forms.ValidationError("content should be longer than title.")

    def clean_content(self):
        content = self.cleaned_data['content']
        sanitized_content = bleach.clean(content, tags=['b', 'i', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'])
        return sanitized_content


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class SignUpFrom(forms.ModelForm):
    password1 = forms.CharField(max_length=50, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=50, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_password2(self):
        p1 = self.cleaned_data['password1']
        p2 = self.cleaned_data['password2']
        if p1 != p2:
            raise forms.ValidationError("PASSWORD DOESNT MATCH")

    def save(self):
        user = User.objects.create_user(username=self.cleaned_data['username'], password=self.cleaned_data['password1'])
        user.email = self.cleaned_data['email']
        user.save()
        return user

Blog/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import CreateView,TemplateView,DetailView
from .forms import BlogForm, LoginForm, SignUpFrom
from .models import Blog
from django.urls import reverse, reverse_lazy
import uuid
from django.contrib import messages
from django.utils.safestring import mark_safe
from bs4 import BeautifulSoup
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin


class MyLoginRequiredMixin(LoginRequiredMixin):
    login_url = reverse_lazy('Blog:login')
    redirect_field_name = 'next'


class HomePage(View):
    ctx = {'action': reverse_lazy('Blog:homepage'), 'id': 'home_page', 'button': 'Save and Done'}

    def get(self, request):
        form = BlogForm()
        return render(request, "Blog/homepage.html", {'form': form, 'ctx': self.ctx})

    def post(self, request):
        form = BlogForm(request.POST)
        if form.is_valid():
            instance = form.save()
            if request.user.is_authenticated:
                instance.author = request.user
                instance.save()
            else:
                instance.secret_key = uuid.uuid4().hex[:6].upper()
                instance.save()
                url_path = reverse('Blog:editPage', kwargs={'id': instance.id, 'secret_key': instance.secret_key})
                messages.success(request, mark_safe("<a href='{url_path}'>{url_path}</a>".format(url_path=url_path)))
            return redirect("Blog:Content", id=instance.id)
        return render(request, "Blog/homepage.html", {'form': form, 'ctx': self.ctx})


class ContentPage(View):

    def get(self, request, id):
        blog = get_object_or_404(Blog, id=id)
        soup = BeautifulSoup(blog.content, "lxml")
        list_of_contents = " "
        soup.body.hidden = True
        soup.html.hidden = True
        for tag in soup.body.find_all(['h1', 'h2', 'h3', 'h4', 'h5', 'h6']):
            tag_text = tag.string
            index = int(tag.name[1])
            list_of_contents += "<ul>"*index + "<li>" + tag_text + "</li>"+"</ul>" * index
        return render(request, "Blog/content.html", {'blog': blog, 'blog_toc': list_of_contents})


class EditPage(View):
    ctx = {'id': 'edit_post', 'button': 'Edit and Save', 'claim_button': 'Claim'}

    def dispatch(self, request, *args, **kwargs):
        if self.kwargs.get('secret_key'):
            self.blog = get_object_or_404(Blog, id=self.kwargs.get('id'), secret_key=self.kwargs.get('secret_key'))
        else:
            self.blog = get_object_or_404(Blog, id=self.kwargs.get('id'), author=request.user)
        return super(EditPage, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = BlogForm(instance=self.blog)
        if request.user.is_authenticated and self.blog.author is None:
            url = reverse('Blog:Claim', kwargs={'id': self.blog.id, 'secret_key': self.blog.secret_key})
            return redirect(url)
        else:
            return render(self.request, "Blog/homepage.html", {'form': form, 'ctx': self.ctx,'blog':self.blog})

    def post(self, request, *args, **kwargs):
        form = BlogForm(self.request.POST or None, instance=self.blog)
        if form.is_valid():
            instance = form.save()
            instance.save()
            return redirect("Blog:Content", id=instance.id)
        return render(self.request, "Blog/homepage.html", {'form': form, 'ctx': self.ctx})


class SignupView(CreateView):
    model = User
    form_class = SignUpFrom
    template_name = 'Blog/signup.html'
    success_url = reverse_lazy('Blog:login')


class LoginView(View):
    ctx = {'id': 'login_form', 'action': reverse_lazy('Blog:login'), 'button': 'LOGIN'}

    def get(self, request):
        form = LoginForm()
        return render(request, "Blog/login.html", {"form": form, 'ctx': self.ctx})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = User.objects.get(username=username)
            if user.check_password(password) and user.is_active:
                login(request, user)
                return redirect("Blog:homepage")
        return render(request, "Blog/login.html", {"form": form, 'ctx': self.ctx})


class LogoutView(View):

    def post(self, request):
        logout(request)
        return redirect("Blog:homepage")


class ArticlesView(MyLoginRequiredMixin, TemplateView):
    template_name = "Blog/articles.html"

    def get_context_data(self, **kwargs):
        context = super(ArticlesView, self).get_context_data(**kwargs)
        context['articles'] = Blog.objects.filter(author=self.request.user)
        return context


class ClaimView(MyLoginRequiredMixin, DetailView):
    model = Blog
    template_name = 'Blog/claim.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Blog, id=self.kwargs.get('id'), secret_key=self.kwargs.get('secret_key'))

    def dispatch(self, request, *args, **kwargs):
        self.blog = self.get_object()
        if not (request.user.is_authenticated and self.blog.author is None):
            raise Http404
        return super(ClaimView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        post = self.get_object()
        post.author = self.request.user
        post.secret_key = ''
        post.save()
        return redirect("Blog:Content", id=post.id)

Blog/templates/Blog/articles.html
{% extends 'Blog/base.html' %}
{% load widget_tweaks %}
{% block title %} ARTICLES {% endblock %}
{% block header %}<b> ANONYMOUS BLOG</b> {% endblock %}
{% block pagecontent %}
<div class="container">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Hai {{request.user.username}} !!!!!!</h4>
          <h6 class="font-weight-bold indigo-text py-2">Your Articles list:</h6>
        <p class="card-text">
            {%for post in articles %}
                {{post|linebreaks}}
                {% if request.user == post.author%}
                    <a href="{% url 'Blog:LogUserEdit' id=post.id %}">Edit</a>
                {% endif %}
            {% endfor %}
        </p>
      </div>
    </div>
</div>
{%endblock%}

Blog/templates/Blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'Blog/style.css' %}" type="text/css">
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
          <ul class="navbar-nav">
              <li class="nav-item active col-sm-12" style="width:700px;">
                <a class="nav-link" href="#">{% block header %}{% endblock %}</a>
              </li>
              <li class="nav-item">
                  <a class="btn btn-link" href="{% url 'Blog:homepage' %}">Home</a>
              </li>
              {% if request.user.is_authenticated %}
                  <li class="nav-item float-right">
                      <a class="btn btn-link" href="{% url 'Blog:mine' %}">/Mine</a>
                  </li>
                  <li class="nav-item float-right">
                      <form method="post" action="{% url 'Blog:logout' %}">
                          {% csrf_token%}
                          <button class="btn btn-link">LOGOUT</button>
                      </form>
                  </li>
              {% else %}
                  <li class="nav-item float-right">
                      <a class="btn btn-link" href="{% url 'Blog:login' %}">Login</a>
                  </li>
                  <li class="nav-item float-right">
                      <a class="btn btn-link" href="{% url 'Blog:signup' %}">SignUp</a>
                  </li>
              {% endif %}
          </ul>
        </nav>

        <main>
            <div id="Wrapper" class="container" style="padding-top : 25px;">
                <form action="{{ctx.action}}" method="post" id="{{ctx.id}}">
                {% csrf_token %}
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors%}
                            {{error}}
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% block pagecontent %}{% endblock %}
                </form>
            </div>
        </main>

        <footer>
            {% block footer %} {% endblock %}
        </footer>
    </body>
</html>

Blog/templates/Blog/claim.html
{% extends 'Blog/base.html' %}
{% load widget_tweaks %}
{% block title %} CLAIM PAGE {% endblock %}
{% block header %}<b> ANONYMOUS BLOG</b> {% endblock %}
{% block pagecontent %}
<div class="container">
    <div class="card">
      <div class="card-body">
          {{obj}}
        <h6 class="font-weight-bold indigo-text py-2">{{object.title}}</h6>
         <p class="card-text">This is an Anonymous Blog: Claim it as Yours</p>
          <form method="post">
            <button type="submit" class="btn btn-primary" onclick="clicked(event)">CLAIM</button>
          </form>
      </div>
    </div>
</div>
<script>
    function clicked(event)
    {
       if (confirm('Do you want to confirm this action?'))
       {
            return true;
       } else
       {
           event.preventDefault();
       }
    }

</script>
{%endblock%}

Blog/templates/Blog/content.html
{% extends 'Blog/base.html' %}
{% block title %}POST{% endblock %}
{% block header %}<b> ANONYMOUS BLOG</b> {% endblock %}
{% block pagecontent %}
<div class="container">
    <div class="form-group">
        <div class="card mt-4">
            <h3 class="card-header success-color white-text">Table of contents</h3>
            <div class="card-body">
                {% autoescape off %}
                    {{blog_toc|linebreaks}}
                {% endautoescape %}
            </div>
        </div>
        {% if request.user.is_authenticated %}
            <div class="container">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title"><a href="{% url 'Blog:LogUserEdit' id=blog.id %}">{{blog.id}}/edit/</a></h4>
                  </div>
                </div>
            </div>
        {% else %}
            <div class="form-group row">
                <div class="col-sm-10">
                    {%if messages %}
                        <div class="messages">
                            {% for message in messages %}
                                <div class="alert alert-success mt-3"  role="alert">
                                    {{message|safe}}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endif %}
        <div class="container text-center">
            <label for="blog_title" class='h3'>Title:</label>
            <div class="d-inline">
                    {{blog.title}}
            </div>
        </div>
        <div class="container text-center">
            <label for="blog_content" class='h2'>Content:</label>
            <div class="d-inline">
                {% autoescape off %}
                    {{blog.content|linebreaks}}
                {% endautoescape %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

Blog/templates/Blog/homepage.html
{% extends 'Blog/base.html' %}
{% load widget_tweaks %}
{% block title %} HOMEPAGE {% endblock %}
{% block header %}<b> ANONYMOUS BLOG</b> {% endblock %}
{% block pagecontent %}
<div class="form-group" id="first">
    <label for="{{form.title.id_for_label}}">Title:</label>
    {% if form.title.errors %}
        {% render_field form.title class="form-control is-invalid" %}
        <div class="invalid-feedback">
             {{form.title.errors}}
        </div>
    {% else %}
        {% render_field form.title class="form-control is-valid" %}
    {% endif %}
</div>

<div class="form-group " id="second">
    <label for="{{form.content.id_for_label}}">content:</label>
    {% if form.content.errors %}
        {% render_field form.content class="form-control is-invalid" %}
        <div class="invalid-feedback">
            {{form.content.errors}}
        </div>
    {% else %}
        {% render_field form.content class="form-control is-valid" %}
    {% endif %}
</div>
<div>
    <button class="btn btn-primary">{{ctx.button}}</button>
</div>
{%endblock%}

Blog/templates/Blog/login.html
{% extends 'Blog/base.html' %}
{% load widget_tweaks %}
{% block title %} LOGIN {% endblock %}
{% block header %}<b> ANONYMOUS BLOG</b> {% endblock %}
{% block pagecontent %}
<div class="form-group">
    <div class="form-group row">
        <label for="{{form.username.id_for_label}}" class="col-md-2">Username:</label>
        <div class="col-md-5">
            {% if form.username.errors %}
                {% render_field form.username class="form-control is-invalid" %}
                <div class="invalid-feedback">
                     {{form.username.errors}}
                </div>
            {% else %}
                {% render_field form.username class="form-control is-valid" %}
            {% endif %}
       </div>
    </div>
</div>

<div class="form-group">
    <div class="form-group row">
        <label for="{{form.password.id_for_label}}" class="col-md-2">Password:</label>
        <div class="col-md-5">
            {% if form.password.errors %}
                {% render_field form.password class="form-control is-invalid" %}
                <div class="invalid-feedback">
                    {{form.password.errors}}
                </div>
            {% else %}
                {% render_field form.password class="form-control is-valid" %}
            {% endif %}
        </div>
    </div>
</div>
<div >
    <button class="btn btn-primary">LOGIN</button>
</div>
{%endblock%}

Blog/templates/Blog/signup.html
{% extends 'Blog/base.html' %}
{% load widget_tweaks %}
{% block title %} SIGNUP {% endblock %}
{% block header %}<b> ANONYMOUS BLOG</b> {% endblock %}
{% block pagecontent %}
<div class="form-group">
    <div class="form-group row">
        <label for="{{form.username.id_for_label}}" class="col-md-2">Username:</label>
        <div class="col-md-5">
            {% if form.username.errors %}
                {% render_field form.username class="form-control is-invalid" %}
                <div class="invalid-feedback">
                     {{form.username.errors}}
                </div>
            {% else %}
                {% render_field form.username class="form-control is-valid" %}
            {% endif %}
       </div>
    </div>
</div>
<div class="form-group">
    <div class="form-group row">
        <label for="{{form.email.id_for_label}}" class="col-md-2">Email:</label>
        <div class="col-md-5">
            {% if form.email_id.errors %}
                {% render_field form.email class="form-control is-invalid" %}
                <div class="invalid-feedback">
                    {{form.email.errors}}
                </div>
            {% else %}
                {% render_field form.email class="form-control is-valid" %}
            {% endif %}
        </div>
    </div>
</div>
<div class="form-group">
    <div class="form-group row">
        <label for="{{form.password1.id_for_label}}" class="col-md-2">Password:</label>
        <div class="col-md-5">
            {% if form.password1.errors %}
                {% render_field form.password1 class="form-control is-invalid" %}
                <div class="invalid-feedback">
                    {{form.password1.errors}}
                </div>
            {% else %}
                {% render_field form.password1 class="form-control is-valid" %}
            {% endif %}
        </div>
    </div>
</div>
<div class="form-group">
    <div class="form-group row">
        <label for="{{form.password2.id_for_label}}" class="col-md-2">Re-Password:</label>
        <div class="col-md-5">
            {% if form.password2.errors %}
                {% render_field form.password2 class="form-control is-invalid" %}
                <div class="invalid-feedback">
                    {{form.password2.errors}}
                </div>
            {% else %}
                {% render_field form.password2 class="form-control is-valid" %}
            {% endif %}
        </div>
    </div>
</div>
<div >
    <button class="btn btn-primary">Signup</button>
</div>
{%endblock%}